services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: avitodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5434:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./dbInit/dbInit.sql:/docker-entrypoint-initdb.d/init.sql
  mockdb:
    image: postgres:16
    environment: 
      POSTGRES_DB: avitomockdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
    ports:
      - "5436:5432"
    volumes:
      - ./.mockdatabase/postgres/data:/var/lib/postgresql/data
      - ./dbInit/dbInit.sql:/docker-entrypoint-initdb.d/init.sql
  main:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db